# Generated by Django 4.2 on 2023-04-07 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_alter_thread_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="thread",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RenameField(
            model_name="message",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="thread",
            name="participants",
            field=models.ManyToManyField(
                related_name="threads", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
